### ISSUE TITLE
Add option to receive data from multiple sources

### ISSUE THREAD

**Issue by dayvsonlima** [hugodemiglio/hg-weather-gem#2]
Add option to receive data from multiple sources. Creating with decorator pattern interface.

So could receive the prediction of multiple APIs, changing only the source

**Comment by hugodemiglio** [comment]
Hi @dayvsonlima,

Thank you for your idea, but this gem is for HG Weather API, It's not a generic gem for weather services.

Regards,
Hugo Demiglio.
